---
version: "3"
services:
  nextcloud:
    image: linuxserver/nextcloud
    container_name: nextcloud
    environment:
      - PUID=1001
      - PGID=1001
      - TZ=America/New_York
    volumes:
      - /path/to/nextcloud/config:/config
      - /path/to/nextcloud/data:/data
    depends_on:
      - mariadb
    restart: unless-stopped
  mariadb:
    image: linuxserver/mariadb
    container_name: mariadb
    environment:
      - PUID=1001
      - PGID=1001
      - MYSQL_ROOT_PASSWORD=<password>
      - TZ=America/New_York
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=<username>
      - MYSQL_PASSWORD=<password>
    volumes:
      - /path/to/mariadb/config:/config
    restart: unless-stopped
  letsencrypt:
    image: linuxserver/swag
    container_name: letsencrypt
    cap_add:
      - NET_ADMIN
    environment:
      - PUID=1001
      - PGID=1001
      - TZ=America/New_York
      - URL=edscloud.org
      - SUBDOMAINS=wildcard
      - VALIDATION=dns
      - DNSPLUGIN=digitalocean
      - EMAIL=your@email.com
    volumes:
      - /path/to/letsencrypt/config:/config
    ports:
      - 443:443
      - 80:80
    restart: unless-stopped
