---
version: "2.1"
services:
  nginx:
    image: lscr.io/linuxserver/nginx
    container_name: nginx
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/New_York
    volumes:
      - /docker/web:/config
      - /docker/web:/config/keys
    ports:
      - 8080:80
      - 8443:443
    restart: unless-stopped
