---
version: "2.1"
services:
    netbootxyz:
      image: lscr.io/linuxserver/netbootxyz
      container_name: netbootxyz
      :wenvironment:
        - PUID=1000
        - PGID=1000
        - MENU_VERSION=1.9.9 #optional
        - PORT_RANGE=30000:30010 
      volumes:
        - /docker/netbootxyz/config:/config
        - /docker/netbootxyz/assets:/assets
      ports:
        - 3000:3000
        - 69:69/udp
        - 8080:80
      
      restart: unless-stopped
