version: "3"

# More info at https://github.com/pi-hole/docker-pi-hole/ and https://docs.pi-hole.net/
services:
  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    hostname: <serverFQDN> 
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "67:67/udp"
      - "80:80/tcp"
    environment:
      TZ: 'America/New_York'
      FTLCONF_REPLY_ADDR4: <serverIP>
      PIHOLE_DNS_: 208.67.222.222;8.8.8.8 # OpenDNS and Google DNS
    # Volumes store your data between container upgrades
    volumes:
            - '/mnt/docker/etc-pihole:/etc/pihole/:z' # 'z' tag for SELinux
            - '/mnt/docker/etc-dnsmasq.d:/etc/dnsmasq.d/:z' # 'z' tag for SELinux
    restart: unless-stopped
