--- # Complete system updates
- hosts: prod
  become: yes
  tasks:
    - name: update dnf packages
      dnf:
        name: '*'
        state: latest
        update_cache: yes
      when:
        - ansible_os_family == "RedHat"
