--- # Complete system updates
- hosts: home
  become: true
  become_user: root
  become_method: su
  tasks:

  - name: update dnf packages
    dnf: 
      name: '*'
      state: latest
      update_cache: yes
    when:
      - ansible_os_family == "RedHat"

  - name: Reboot the server
    ansible.builtin.reboot:
      pre_reboot_delay: 65
      reboot_timeout: 120
